name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: All things angular
        uses: AhsanAyaz/angular-deploy-gh-pages-actions@[version] ## replace by latest version without it you will see Expected format {org}/{repo}[/path]@ref. Actual 'AhsanAyaz/angular-deploy-gh-pages-actions',Input string was not in a correct format.
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }} # see the Configuration section for how you can create secrets
          build_configuration: development # The build environment for the app. please look configurations in your angular.json
          base_href: /spirit-haven/ # make sure this corresponds to https://<your_username>.github.io/<base_href>/
          deploy_branch: gh-pages # The branch the action should deploy to.
          angular_dist_build_folder: dist/spirit-haven # The folder where your project is supposed to be after running ng build by the action.

permissions:
  contents: write # Allow write permission to GITHUB_TOKEN to commit to deploy branch.

# name: angular-build

# on:
#   push:
#     branches:
#       - "main"

# jobs:
#   build:
#     name: build
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#       - name: Use Node 18.x
#         uses: actions/setup-node@v1
#         with:
#           node-version: "18.x"
#       - name: Install dependencies
#         run: npm ci
#       - name: Build
#         run: npm run build:ci
#       - name: Archive build
#         if: success()
#         uses: actions/upload-artifact@v1
#         with:
#           name: deploy_dist
#           path: dist
#   deploy:
#     runs-on: ubuntu-latest
#     needs: build
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v1
#       - name: Download build
#         uses: actions/download-artifact@v1
#         with:
#           name: deploy_dist
#       - name: Deploy to GitHub Pages
#         uses: JamesIves/github-pages-deploy-action@releases/v3
#         with:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           BRANCH: gh-pages
#           FOLDER: deploy_dist/spirit-haven
